version: "3.4"

services:
  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - "EVENTSTORE_INSECURE=true"
      - "EVENTSTORE_EXT_TCP_PORT=1113"
      - "EVENTSTORE_HTTP_PORT=2113"
      - "EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true"
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - "eventstore-data:/var/lib/eventstore"
      - "eventstore-logs:/var/log/eventstore"

volumes:
  eventstore-data:
  eventstore-logs: